version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "movieappapi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1tarjpaulzd16"
s3_prefix = "movieappapi"
region = "us-east-1"
profile = "ravish"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

